/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi_screen_example;
import multi_screen_example.controller.ExampleController;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new ExampleController();
    }
}
